service: ubc-course-sub
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    STAGE: ${sls:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchGetItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - ses:SendTemplatedEmail
      Resource:
        - "arn:aws:dynamodb:${aws:region}:*:table/*"
        - "arn:aws:ses:${aws:region}:*:identity/*"
        - "arn:aws:ses:${aws:region}:*:template/*"

functions:
  test:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  refresh:
    handler: Handlers/RefreshHandler.refreshHandler
    events:
      - httpApi:
          path: /api/refresh
          method: get
  subscribe:
    handler: Handlers/SubscribeHandler.subscribeHandler
    events:
      - httpApi:
          path: /api/subscribe
          method: post
  unsubscribe:
    handler: Handlers/UnsubscribeHandler.unsubscribeHandler
    events:
      - httpApi:
          path: /api/unsubscribe/{userEmail}/{courseId}
          method: delete

resources:
  Resources:
    CourseTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ubc-course-sub-${sls:stage}-course
        AttributeDefinitions:
          - AttributeName: courseId
            AttributeType: S
          - AttributeName: subscriberEmail
            AttributeType: S
        KeySchema:
          - AttributeName: courseId
            KeyType: HASH
          - AttributeName: subscriberEmail
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: subscriberEmail
            KeySchema:
              - AttributeName: subscriberEmail
                KeyType: HASH
              - AttributeName: courseId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 2
              WriteCapacityUnits: 2
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

    SeatsRemainingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ubc-course-sub-${sls:stage}-seats-remaining
        AttributeDefinitions:
          - AttributeName: courseId
            AttributeType: S
        KeySchema:
          - AttributeName: courseId
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

